from .handler import CustomException


class UserException(CustomException):
    pass
